<Background>:
    id: background
    canvas.before:
        Rectangle:
            size: self.size
            pos: self.pos
            source: "background2.png"
        Rectangle:
            size: self.width, 200
            pos: self.pos[0], self.pos[1] + self.height - 150
            texture: self.cloud_texture
        Rectangle:
            size: self.width, 250
            pos: self.pos[0], self.pos[1]
            texture: self.floor_texture
