<Mylayout>:
    orientation: "vertical"
    padding: 500
    spacing: 500

    Label:
        id: Flappy
        text: "Choose the game you want"
        font_size: 32

    Button:
        text: "Hello"
        font_size: 32
        size_hint: .15, 12000000000000  
        background_color:0,0,0,0,
        pos_hint:{'center_x':0.5}
        Image:
            source: 'Flappyinter.png'
            center_x: self.parent.center_x
            center_y: self.parent.center_y
